"""remove_currency_from_assets

Revision ID: 92f125cb67c9
Revises: dd7ad94ae14a
Create Date: 2026-03-17 02:25:25.342408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f125cb67c9'
down_revision: Union[str, Sequence[str], None] = 'dd7ad94ae14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'currency')
    op.drop_column('investment_transactions', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transactions', sa.Column('note', sa.TEXT(), nullable=True))
    op.add_column('assets', sa.Column('currency', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
