export const ErrorCode = {
  // Not Found
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  EXCHANGE_RATE_NOT_FOUND: 'EXCHANGE_RATE_NOT_FOUND',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_DATE: 'INVALID_DATE',

  // Business Rule
  INVALID_TRANSACTION_TYPE: 'INVALID_TRANSACTION_TYPE',
  CATEGORY_TYPE_MISMATCH: 'CATEGORY_TYPE_MISMATCH',
  SAME_CURRENCY_EXCHANGE_RATE: 'SAME_CURRENCY_EXCHANGE_RATE',
  MISSING_EXCHANGE_RATE: 'MISSING_EXCHANGE_RATE',
  INVALID_ACCOUNT_LINK: 'INVALID_ACCOUNT_LINK',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  SELF_TRANSFER: 'SELF_TRANSFER',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  // Conflict
  DUPLICATE_ACCOUNT_NAME: 'DUPLICATE_ACCOUNT_NAME',
  DUPLICATE_CATEGORY_NAME: 'DUPLICATE_CATEGORY_NAME',
  DUPLICATE_EXCHANGE_RATE: 'DUPLICATE_EXCHANGE_RATE',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  TRANSACTION_BELONGS_TO_TRANSFER: 'TRANSACTION_BELONGS_TO_TRANSFER',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
